### PR TITLE
CC-1360: Enable enhanced avro schema support by default in storage sink connectors

### PR DESCRIPTION
**Pull request by kkonstantine**
## Problem
Changing the default required the release of a major version

## Solution
Switch the default to enhanced avro schema support

##### Does this solution apply anywhere else?
- [ ] yes
- [ ] no

##### Testing done:
- [x] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

## Release Plan

 
Only 10.0.x and beyond

### CODE REVIEW

**Review by dosvath — COMMENTED** [review]
Before moving forward, I have a few questions:

- It looks like Enhanced Avro Schema support appears as `false` default in multiple of our docs. [Schema registry docs](https://docs.confluent.io/current/schema-registry/connect.html), [S3 Sink docs](https://docs.confluent.io/current/connect/kafka-connect-s3/configuration_options.html). 
- We should also make sure to consider issues [like this enum handling issue](https://github.com/confluentinc/schema-registry/issues/658) when using enhanced schema support to avoid possible problems with AvroData in our sink connectors. 
- What is the reasoning behind turning this default to `true`?

**Comment by kkonstantine** [comment]
Thanks for the review @dosvath 

> * It looks like Enhanced Avro Schema support appears as `false` default in multiple of our docs. [Schema registry docs](https://docs.confluent.io/current/schema-registry/connect.html), [S3 Sink docs](https://docs.confluent.io/current/connect/kafka-connect-s3/configuration_options.html).

The docs are in a separate repo.

> * We should also make sure to consider issues [like this enum handling issue](https://github.com/confluentinc/schema-registry/issues/658) when using enhanced schema support to avoid possible problems with AvroData in our sink connectors.

We are not removing the config here. We are just turning it on by default. Users have still the ability to turn it off. 

> * What is the reasoning behind turning this default to `true`? 

This config has been introduced a while back. It's potentially an incompatible change for users, so it had to wait for a major version release to be switched from `false` to `true`. But enabling it, is the mainstream behavior we want to have. 

> In general I feel cautious about enabling a feature by default that used to be off due to the possibility of breaking changes with users' existing connector configurations.

That's why we waited for a major release.

**Review by dosvath — APPROVED** [review]
Thanks for the answers, makes sense 👍

**Comment by dosvath** [comment]
LGTM

**Pull request merged**
