### PR TITLE
CC-22820, CC-22998, CC-23052: Fix avro and snappy CVEs

### PR DESCRIPTION
**Pull request by sambhav-jain-16**
## Problem
https://confluentinc.atlassian.net/browse/CC-22820
https://confluentinc.atlassian.net/browse/CC-22998
https://confluentinc.atlassian.net/browse/CC-23052

## Solution
Bump common

##### Does this solution apply anywhere else?
- [ ] yes
- [ ] no

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

### CODE REVIEW

**Review by venkatteki — APPROVED** [review]
lgtm

**Comment by venkatteki** [comment]
@sambhav-jain-16 dont we need these fixes in older feature branches?

**Comment by sambhav-jain-16** [comment]
@venkatteki no, the CVE was only for master branch

**Comment by venkatteki** [comment]
> @venkatteki CVEs were only for master branch

Some connectors might be using storage-commons right? Don't we need a new release for this repo to update in the connector repos?

**Pull request merged**
