### PR TITLE
CCMSG-2388: Bump protobuf.version to 3.19.6 to resolve CVEs

### PR DESCRIPTION
**Pull request by aniketshrimal**
## Problem
- https://confluentinc.atlassian.net/browse/CCMSG-2388
- Protobuf version 3.19.4 has vulnerabilities.

## Solution
- Bring updated protobuf dependency from parent pom. 

Reference - https://github.com/confluentinc/kafka-connect-elasticsearch/pull/419

##### Does this solution apply anywhere else?
- [ ] yes
- [ ] no

##### Testing done:
- [ ] Unit tests
- [ ] Integration tests
- [ ] System tests
- [ ] Manual tests

### CODE REVIEW

**Review by pbadani — APPROVED** [review]

**Comment by pbadani** [comment]
Would unpinning the version here pick it up from the parent? example:
https://github.com/confluentinc/kafka-connect-storage-common/pull/285/files

**Comment by aniketshrimal** [comment]
> Would unpinning the version here pick it up from the parent? example:
https://github.com/confluentinc/kafka-connect-storage-common/pull/285/files

I just checked - parent(common) was updated long time ago with this protobuf version. So it should be possible to pull in the dependency from parent. Let me make that change. Thanks for pointing that out. 

@pbadani  - I have another question - the build seems to be failing with following error - 
```
Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:spotbugs (spotbugs) on project kafka-connect-storage-common: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:spotbugs failed: Java returned: 1 -> [Help 1]
```
Do u have any idea around this error?

**Comment by pbadani** [comment]
> > Would unpinning the version here pick it up from the parent? example:
> > https://github.com/confluentinc/kafka-connect-storage-common/pull/285/files
> 
> I just checked - parent(common) was updated long time ago with this protobuf version. So it should be possible to pull in the dependency from parent. Let me make that change. Thanks for pointing that out.
> 
> @pbadani - I have another question - the build seems to be failing with following error -
> 
> ```
> Failed to execute goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:spotbugs (spotbugs) on project kafka-connect-storage-common: Execution spotbugs of goal com.github.spotbugs:spotbugs-maven-plugin:4.0.0:spotbugs failed: Java returned: 1 -> [Help 1]
> ```
> 
> Do u have any idea around this error?

There should be an Intellij plugin for this.

**Review by pbadani — APPROVED** [review]

**Comment by aniketshrimal** [comment]
Raised a PR to fix build errors here - https://github.com/confluentinc/kafka-connect-storage-common/pull/302

**Pull request merged**
